# Generated by Django 5.0 on 2023-12-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorintroductionpage',
            name='page_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ページのタイトル(メンター紹介)'),
        ),
    ]
