# Generated by Django 5.0 on 2024-01-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(0, '通塾生'), (1, '体験')], default=0, help_text='Select an option from the dropdown.', max_length=255),
        ),
    ]
