# Generated by Django 5.0 on 2023-12-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='intro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='フォームのタイトル(例:お問合せ)'),
        ),
    ]
