# Generated by Django 5.0 on 2023-12-28 12:06

import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_contentsdetailpage_contents_name_and_more'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='テキストの説明'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='text_name',
            field=models.CharField(max_length=100, verbose_name='テキストのタイトル'),
        ),
        migrations.AddField(
            model_name='textpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='contents.textcategory'),
        ),
    ]
