# Generated by Django 5.0 on 2024-01-01 13:19

import django.db.models.deletion
import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_textcategory_options_alter_textpage_body_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, verbose_name='テキストの本文'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='カバー画像'),
        ),
    ]
