# Generated by Django 5.0 on 2024-01-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_remove_textpage_categories_textpage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contents.textcategory', verbose_name='コンテンツのカテゴリ選択'),
        ),
    ]
