# Generated by Django 5.0 on 2024-01-10 10:50

import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_textpage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsdetailpage',
            name='contents_name',
            field=models.CharField(max_length=100, verbose_name='コンテンツのタイトル(例:Unity など)'),
        ),
        migrations.AlterField(
            model_name='contentsselectingpage',
            name='page_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ここには”コンテンツ一覧”と入力してください'),
        ),
        migrations.AlterField(
            model_name='textpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True, verbose_name='テキストの本文(マークダウン形式でご入力下さい)'),
        ),
    ]
