# Generated by Django 5.0 on 2024-01-27 13:09

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_alter_contentsdetailpage_contents_name_and_more'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsdetailpage',
            name='note',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='contentsselectingpage',
            name='page_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ここには”コンテンツ一覧”と入力'),
        ),
        migrations.CreateModel(
            name='ContentsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='contents.contentsdetailpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contentsdetailpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='contents.ContentsTag', to='taggit.Tag', verbose_name='タグ'),
        ),
    ]
