# Generated by Django 5.0 on 2024-01-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('particular', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='particularblock',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='カバー画像'),
        ),
        migrations.AddField(
            model_name='particularblock',
            name='description',
            field=models.TextField(blank=True, verbose_name='作成フローの詳細文'),
        ),
        migrations.DeleteModel(
            name='ParticularItem',
        ),
    ]
