# Generated by Django 5.0 on 2024-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creationflowblock',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='creationflowblock',
            name='sub_title1',
            field=models.CharField(default='', max_length=255, verbose_name='サブタイトル1行目(例:導入の)'),
        ),
        migrations.AddField(
            model_name='creationflowblock',
            name='sub_title2',
            field=models.CharField(default='', max_length=255, verbose_name='サブタイトル2行目(例:導入の20分)'),
        ),
        migrations.AddField(
            model_name='creationflowblock',
            name='sub_title_color',
            field=models.CharField(choices=[('#BDE3FF', 'スカイブルー'), ('#FCD19C', 'オレンジ'), ('#FCC7C2', 'ピンク'), ('#99FF99', 'グリーン'), ('#C299FF', 'パープル'), ('#FFFF99', 'イエロー'), ('#FFFFFF', 'ホワイト'), ('#CCCCCC', 'グレー')], default='#BDE3FF', max_length=255, verbose_name='サブタイトルの背景カラー'),
        ),
        migrations.AlterField(
            model_name='creationflow',
            name='page_title',
            field=models.CharField(max_length=255, verbose_name='ページのタイトル(作成の流れ)'),
        ),
    ]
