# Generated by Django 5.0 on 2024-01-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name1', models.CharField(max_length=255, verbose_name='お子様の氏名(漢字)')),
                ('child_name2', models.CharField(max_length=255, verbose_name='お子様の氏名(ふりがな)')),
                ('parent_name1', models.CharField(max_length=255, verbose_name='保護者の氏名(漢字)')),
                ('parent_name2', models.CharField(max_length=255, verbose_name='保護者の氏名(ふりがな)')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=255, verbose_name='電話番号')),
                ('contact_category', models.CharField(max_length=255, verbose_name='お問い合わせ内容選択')),
                ('comment', models.TextField(verbose_name='自由記入欄')),
            ],
        ),
    ]
