# Generated by Django 5.0 on 2024-01-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255, verbose_name='カテゴリ名を設定')),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='contact_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_form.contactcategory', verbose_name='お問い合わせ内容選択'),
        ),
    ]
