# Generated by Django 5.0 on 2024-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_alter_contactform_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='comment',
            field=models.TextField(null=True, verbose_name='自由記入欄'),
        ),
    ]
