# Generated by Django 5.0 on 2024-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0004_alter_contactform_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='comment',
            field=models.TextField(verbose_name='自由記入欄'),
        ),
    ]
