# Generated by Django 5.0 on 2024-01-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_rename_event_cover_image_leanitem_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leanitem',
            old_name='discription',
            new_name='description',
        ),
    ]
