# Generated by Django 5.0 on 2024-01-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_rename_discription_leanitem_description'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeanItem',
            new_name='LearnItem',
        ),
        migrations.RenameModel(
            old_name='LaenItemList',
            new_name='LearnItemList',
        ),
    ]
