# Generated by Django 5.0 on 2024-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_rename_leanitem_learnitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnitemlist',
            name='page_title',
            field=models.CharField(max_length=255, verbose_name='ページのタイトル(身につくこと)'),
        ),
    ]
