# Generated by Django 5.0 on 2024-01-15 11:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialflowblock',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='体験の流れの詳細文'),
        ),
    ]
