# Generated by Django 5.0 on 2024-01-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_flow', '0002_alter_trialflowblock_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialflowblock',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='trialflowblock',
            name='sub_title1',
            field=models.CharField(default='', max_length=255, verbose_name='サブタイトル(例:STEP1)'),
        ),
        migrations.AddField(
            model_name='trialflowblock',
            name='sub_title2',
            field=models.CharField(default='', max_length=255, verbose_name='サブタイトル(例:導入の20分)'),
        ),
        migrations.AlterField(
            model_name='trialflowblock',
            name='sub_title_color',
            field=models.CharField(choices=[('#BDE3FF', 'スカイブルー'), ('#FCD19C', 'オレンジ'), ('#FCC7C2', 'ピンク'), ('#99FF99', 'グリーン'), ('#C299FF', 'パープル'), ('#FFFF99', 'イエロー'), ('#FFFFFF', 'ホワイト'), ('#CCCCCC', 'グレー')], default='#BDE3FF', max_length=255, verbose_name='サブタイトルの背景カラー'),
        ),
    ]
