# Generated by Django 5.0 on 2024-01-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial_class_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='start_tiem',
            new_name='start_time',
        ),
    ]
