# Generated by Django 5.0 on 2024-01-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_class_reservation', '0002_rename_start_tiem_timeslot_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='コンテンツ名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='available',
            field=models.BooleanField(default=True, verbose_name='予約可否'),
        ),
    ]
