# Generated by Django 5.0 on 2024-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial_class_reservation', '0006_alter_reservationform_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='自由記入欄'),
        ),
    ]
